name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Runs daily at 16:00 UTC

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rmq-version: ['v3.13.7', 'v4.2.x', 'v4.3.x', 'main']
        include:
          - rmq-version: 'main'
            otp-version: 28
            elixir-version: 1.18
          - rmq-version: 'v4.3.x'
            otp-version: 27
            elixir-version: 1.18
          - rmq-version: 'v4.2.x'
            otp-version: 27
            elixir-version: 1.18
          - rmq-version: 'v3.13.7'
            otp-version: 26
            elixir-version: 1.16
    steps:
      - id: restore-rabbitmq-server-cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ github.workspace }}/rabbitmq-server
          key: rmq-${{ matrix.rmq-version }}-otp-${{ matrix.otp-version }}-elixir-${{ matrix.elixir-version }}
      - id: maybe-fail-rabbitmq-server-miss
        if: steps.restore-rabbitmq-server-cache.outputs.cache-hit != 'true'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.setFailed('could not restore cached rabbitmq-server build');
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: rabbitmq-server/deps/aws
      - run: make -C ${{ github.workspace }}/rabbitmq-server/deps/aws
      - run: make -C ${{ github.workspace }}/rabbitmq-server/deps/aws tests
