name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Runs daily at 16:00 UTC

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rmq-version: ['v3.13.7', 'v4.2.x', 'main']
        include:
          - rmq-version: 'main'
            otp-version: 28
            elixir-version: 1.18
          - rmq-version: 'v4.2.x'
            otp-version: 27
            elixir-version: 1.18
          - rmq-version: 'v3.13.7'
            otp-version: 26
            elixir-version: 1.16
    steps:
      - id: restore-rabbitmq-server-cache
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ github.workspace }}/rabbitmq-server
          key: rmq-${{ matrix.rmq-version }}-otp-${{ matrix.otp-version }}-elixir-${{ matrix.elixir-version }}
      - id: maybe-fail-rabbitmq-server-miss
        if: steps.restore-rabbitmq-server-cache.outputs.cache-hit != 'true'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            core.setFailed('could not restore cached rabbitmq-server build');
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: rabbitmq-server/deps/aws
      - run: make -C ${{ github.workspace }}/rabbitmq-server/deps/aws
      - run: make -C ${{ github.workspace }}/rabbitmq-server/deps/aws tests
