name: erlfmt

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: 26
          rebar3-version: 3.22
      - run: |
          git clone https://github.com/WhatsApp/erlfmt.git ${{ github.workspace }}/erlfmt
          cd ${{ github.workspace }}/erlfmt && rebar3 as release escriptize
      - name: Run erlfmt check
        run: ${{ github.workspace }}/erlfmt/_build/release/bin/erlfmt -c
