name: erlfmt

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: 26
          rebar3-version: 3.22
      - run: |
          git clone https://github.com/WhatsApp/erlfmt.git ${{ github.workspace }}/erlfmt
          cd ${{ github.workspace }}/erlfmt && rebar3 as release escriptize
      - name: Run erlfmt check
        run: ${{ github.workspace }}/erlfmt/_build/release/bin/erlfmt -c
