name: erlfmt

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: 26
          rebar3-version: 3.22
      - run: |
          git clone https://github.com/WhatsApp/erlfmt.git ${{ github.workspace }}/erlfmt
          cd ${{ github.workspace }}/erlfmt && rebar3 as release escriptize
      - name: Run erlfmt check
        run: ${{ github.workspace }}/erlfmt/_build/release/bin/erlfmt -c
